### PR TITLE
docs: :memo: remove extra white space in name

### PR DESCRIPTION
**Pull request by PolarWolf314**
The file `1 — Goals.md` had an extra white space between the em dash and `Goals.md`.

I removed this white space for you. Make sure you double check your file names next time!

❤️

### CODE REVIEW

**Review by pumbas600 — APPROVED** [review]
Good catch! I know James will appreciate this :)

**Comment by JamesNZL** [comment]
bruh(s)

**Comment by JamesNZL** [comment]
how

**Comment by JamesNZL** [comment]
https://github.com/JamesNZL/algovision/commit/67f118adb85f930a9952adecb1e0439d911004e3 :^)

you aren't becoming a contributor xoxoxo

**Review by JamesNZL — APPROVED** [review]

**Review by JamesNZL — APPROVED** [review]

**Pull request closed without merging**
